### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by AndreCL** [NikolaDespotoski/DrawerLayoutToggles#3]
Hi, 
Sorry to write this here. Not really an issue. I am learning to use android and I wanted to try to add this to a project. The instructions say "Import the library project and set it to your project.". How do I do that?

**Comment by NikolaDespotoski** [comment]
It is referred to import it as Library Project. See instructions on Android
Developers how to do it in Eclipse and Android Studio.

On 12 March 2015 at 09:23, Andre notifications@github.com wrote:

> Hi,
> Sorry to write this here. Not really an issue. I am learning to use
> android and I wanted to try to add this to a project. The instructions say
> "Import the library project and set it to your project.". How do I do that?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NikolaDespotoski/DrawerLayoutToggles/issues/3.

## 

Google+: https://plus.google.com/117795516319858933
https://plus.google.com/+NikolaDespotoski
Facebook: http://www.facebook.com/nikola.despotoski
StackOverflow: http://stackoverflow.com/users/557179/nikola-despotoski
GitHub: https://github.com/NikolaDespotoski
Skype: nikola.despotoski
Mobile: +389 78 515 738
Time Zone: UTC+01:00
